// Generated from the swap product's chain catalogue. Local icons live in public/assets/chains.
export const CHAIN_CATALOGUE = [
  {
    id: "near",
    name: "Near",
    symbol: "NEAR",
    decimals: 24,
    logo: "/assets/chains/near.svg",
    explorer: "https://explorer.near.org",
  },
  {
    id: "eth",
    name: "Ethereum",
    symbol: "ETH",
    decimals: 18,
    logo: "/assets/chains/ethereum.svg",
    explorer: "https://etherscan.io",
  },
  {
    id: "scroll",
    name: "Scroll",
    symbol: "ETH",
    decimals: 18,
    logo: "/assets/chains/scroll.png",
    explorer: "https://scrollscan.com",
  },
  {
    id: "base",
    name: "Base",
    symbol: "ETH",
    decimals: 18,
    logo: "/assets/chains/base.svg",
    explorer: "https://basescan.org",
  },
  {
    id: "arb",
    name: "Arbitrum",
    symbol: "ETH",
    decimals: 18,
    logo: "/assets/chains/arbitrum.svg",
    explorer: "https://arbiscan.io",
  },
  {
    id: "bsc",
    name: "BNB Smart Chain",
    symbol: "BNB",
    decimals: 18,
    logo: "/assets/chains/bsc.svg",
    explorer: "https://bscscan.com",
  },
  {
    id: "pol",
    name: "Polygon",
    symbol: "MATIC",
    decimals: 18,
    logo: "/assets/chains/polygon.svg",
    explorer: "https://polygonscan.com",
  },
  {
    id: "sol",
    name: "Solana",
    symbol: "SOL",
    decimals: 9,
    logo: "/assets/chains/solana.svg",
    explorer: "https://explorer.solana.com",
  },
  {
    id: "fogo",
    name: "Fogo",
    symbol: "FOGO",
    decimals: 9,
    logo: "https://coin-images.coingecko.com/coins/images/68100/large/fogo_AppIcon.png?1767721208",
    explorer: "https://fogoscan.com",
  },
  {
    id: "ton",
    name: "Toncoin",
    symbol: "TON",
    decimals: 9,
    logo: "/assets/chains/ton.svg",
    explorer: "https://tonscan.org",
  },
  {
    id: "doge",
    name: "Dogecoin",
    symbol: "DOGE",
    decimals: 8,
    logo: "/assets/chains/dogecoin.svg",
    explorer: "https://dogechain.info",
  },
  {
    id: "dash",
    name: "Dash",
    symbol: "DASH",
    decimals: 8,
    logo: "/assets/chains/dash.png",
    explorer: "https://chainz.cryptoid.info/dash/",
  },
  {
    id: "xrp",
    name: "XRP",
    symbol: "XRP",
    decimals: 6,
    logo: "/assets/chains/xrpledger.svg",
    explorer: "https://xrpscan.com",
  },
  {
    id: "zec",
    name: "Zcash",
    symbol: "ZEC",
    decimals: 8,
    logo: "/assets/chains/zcash-icon-black.svg",
    explorer: "https://explorer.zcha.in",
  },
  {
    id: "gnosis",
    name: "Gnosis",
    symbol: "xDAI",
    decimals: 18,
    logo: "/assets/chains/gnosis.svg",
    explorer: "https://gnosisscan.io",
  },
  {
    id: "bera",
    name: "Berachain",
    symbol: "BERA",
    decimals: 18,
    logo: "/assets/chains/berachain.svg",
    explorer: "https://artio.beratrail.io",
  },
  {
    id: "tron",
    name: "Tron",
    symbol: "TRX",
    decimals: 6,
    logo: "/assets/chains/tron.svg",
    explorer: "https://tronscan.org",
  },
  {
    id: "op",
    name: "Optimism",
    symbol: "ETH",
    decimals: 18,
    logo: "/assets/chains/optimism.svg",
    explorer: "https://optimistic.etherscan.io",
  },
  {
    id: "avax",
    name: "Avalanche",
    symbol: "AVAX",
    decimals: 18,
    logo: "/assets/chains/avalanche.svg",
    explorer: "https://snowtrace.io",
  },
  {
    id: "aptos",
    name: "Aptos",
    symbol: "APT",
    decimals: 8,
    logo: "/assets/chains/aptos.png",
    explorer: "https://explorer.aptoslabs.com",
  },
  {
    id: "btc",
    name: "Bitcoin",
    symbol: "BTC",
    decimals: 8,
    logo: "/assets/chains/bitcoin.webp",
    explorer: "https://blockchain.com",
  },
  {
    id: "sui",
    name: "Sui",
    symbol: "SUI",
    decimals: 9,
    logo: "/assets/chains/sui.svg",
    explorer: "https://suiexplorer.com",
  },
  {
    id: "cardano",
    name: "Cardano",
    symbol: "ADA",
    decimals: 8,
    logo: "/assets/chains/cardano.svg",
    explorer: "https://cardanoscan.io",
  },
  {
    id: "ltc",
    name: "Litecoin",
    symbol: "LTC",
    decimals: 8,
    logo: "/assets/chains/ltc.png",
    explorer: "https://litecoinspace.org/",
  },
  {
    id: "monad",
    name: "Monad",
    symbol: "MON",
    decimals: 8,
    logo: "/assets/chains/monad.png",
    explorer: "https://monadvision.com",
  },
  {
    id: "starknet",
    name: "Starknet",
    symbol: "STRK",
    decimals: 18,
    logo: "/assets/chains/starknet.png",
    explorer: "https://starkscan.co",
  },
  {
    id: "stellar",
    name: "Stellar",
    symbol: "XLM",
    decimals: 7,
    logo: "/assets/chains/stellar.svg",
    explorer: "https://stellar.expert",
  },
  {
    id: "xlayer",
    name: "X Layer",
    symbol: "OKB",
    decimals: 18,
    logo: "/assets/chains/xlayer.png",
    explorer: "https://www.okx.com/web3/explorer/xlayer",
  },
  {
    id: "plasma",
    name: "Plasma",
    symbol: "XPL",
    decimals: 18,
    logo: "/assets/chains/plasma.png",
    explorer: "https://plasmascan.io",
  },
  {
    id: "bch",
    name: "Bitcoin Cash",
    symbol: "BCH",
    decimals: 8,
    logo: "/assets/chains/bch.png",
    explorer: "https://blockchair.com/bitcoin-cash",
  },
  {
    id: "adi",
    name: "ADI",
    symbol: "ADI",
    decimals: 18,
    logo: "/assets/chains/adi.png",
    explorer: "https://explorer.adifoundation.ai/",
  },
  {
    id: "abs",
    name: "Abstract",
    symbol: "ETH",
    decimals: 18,
    logo: "https://icons.llamao.fi/icons/chains/rsz_abstract.jpg",
    explorer: "https://abscan.org",
  },
  {
    id: "aleo",
    name: "Aleo",
    symbol: "ALEO",
    decimals: 6,
    logo: "https://coin-images.coingecko.com/coins/images/27916/large/secondary-icon-dark.png",
    explorer: "https://aleo.info",
  },
  {
    id: "hypercore",
    name: "HyperCore",
    symbol: "HYPE",
    decimals: 18,
    logo: "/assets/chains/hyperliquid.svg",
    explorer: "https://hyperevmscan.io",
  },
  {
    id: "hood",
    name: "Robinhood Chain",
    symbol: "ETH",
    decimals: 18,
    logo: "https://cdn.robinhood.com/assets/generated_assets/hoodchain_docsite/chain/brand-guidelines/feather-symbol.png",
    explorer: "https://robinhoodchain.blockscout.com",
  },
  {
    id: "movement",
    name: "Movement",
    symbol: "MOVE",
    decimals: 8,
    logo: "https://coin-images.coingecko.com/coins/images/39345/large/movement-testnet-token.png?1721878759",
    explorer: "https://explorer.movementnetwork.xyz/?network=mainnet",
  },
] as const;
